#!/usr/bin/env bash

ROOT_DIR="$(git rev-parse --show-toplevel)"

URLS=(
    "https://www.home-assistant.io/dashboards/alarm-panel/"
    "https://www.home-assistant.io/dashboards/area/"
    "https://www.home-assistant.io/dashboards/button/"
    "https://www.home-assistant.io/dashboards/calendar/"
    "https://www.home-assistant.io/dashboards/conditional/"
    "https://www.home-assistant.io/dashboards/energy/"
    "https://www.home-assistant.io/dashboards/entities/"
    "https://www.home-assistant.io/dashboards/entity/"
    "https://www.home-assistant.io/dashboards/entity-filter/"
    "https://www.home-assistant.io/dashboards/gauge/"
    "https://www.home-assistant.io/dashboards/glance/"
    "https://www.home-assistant.io/dashboards/grid/"
    "https://www.home-assistant.io/dashboards/history-graph/"
    "https://www.home-assistant.io/dashboards/horizontal-stack/"
    "https://www.home-assistant.io/dashboards/humidifier/"
    "https://www.home-assistant.io/dashboards/light/"
    "https://www.home-assistant.io/dashboards/logbook/"
    "https://www.home-assistant.io/dashboards/map/"
    "https://www.home-assistant.io/dashboards/markdown/"
    "https://www.home-assistant.io/dashboards/media-control/"
    "https://www.home-assistant.io/dashboards/picture/"
    "https://www.home-assistant.io/dashboards/picture-elements/"
    "https://www.home-assistant.io/dashboards/picture-entity/"
    "https://www.home-assistant.io/dashboards/picture-glance/"
    "https://www.home-assistant.io/dashboards/plant-status/"
    "https://www.home-assistant.io/dashboards/sensor/"
    "https://www.home-assistant.io/dashboards/shopping-list/"
    "https://www.home-assistant.io/dashboards/statistic/"
    "https://www.home-assistant.io/dashboards/statistics-graph/"
    "https://www.home-assistant.io/dashboards/thermostat/"
    "https://www.home-assistant.io/dashboards/tile/"
    "https://www.home-assistant.io/dashboards/vertical-stack/"
    "https://www.home-assistant.io/dashboards/weather-forecast/"
    "https://www.home-assistant.io/dashboards/iframe/"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/alarm-control-panel.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/cover.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/entity.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/fan.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/light.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/person.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/template.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/chips.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/title.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/update.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/vacuum.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/media-player.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/lock.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/humidifier.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/climate.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/select.md"
    "https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/number.md"
)

echo "${URLS[@]}" | tr ' ' '\n' | parallel -j 16 "${ROOT_DIR}/card_type.sh"
